### ISSUE TITLE
SparkyCI build fails - do you need Ruby support?

### ISSUE THREAD

**Issue by melezhik** [delonnewman/invokable#8]
Hi @delonnewman  I noticed you run SparkyCI build for this repo - http://sparrowhub.io:2222/report/118 and it fails for the obvious reason that SparkyCI does not yet support Ruby projects ( only Raku ones ). 

However in my roadmap is to support other languages. Are you interested in trying out the SparkyCI? if so, please create a ticket in SparkyCI GH repo on adding Ruby support.

Thanks

Aleksei

**Comment by delonnewman** [comment]
@melezhik Sorry for my slow reply, but I was just playing around.  I'm very pleased seeing so much progress in the Raku community.  I would love to help, but I'm afraid I wouldn't have much time.
